Public Interface ISyntaxTreeVisitor(Of T)
    Function Visit(argument As Argument) As T
    Function Visit(arrayLiteral As ArrayLiteralExpression) As T
    Function Visit(arrayTypeName As ArrayTypeName) As T
    Function Visit(assignment As AssignmentStatement) As T
    Function Visit(binary As BinaryExpression) As T
    Function Visit(booleanLiteral As BooleanLiteralExpression) As T
    Function Visit(bracketExp As BracketExpression) As T
    Function Visit(callExp As CallExpression) As T
    Function Visit(castExp As CastExpression) As T
    Function Visit(charLiteral As CharLiteral) As T
    Function Visit(cu As CompilationUnit) As T
    Function Visit(conceptConstraint As ConceptConstraintClause) As T
    Function Visit(conceptDecl As ConceptDeclaration) As T
    Function Visit(conceptDef As ConceptDefinition) As T
    Function Visit(concreteDecl As ConcreteDeclaration) As T
    Function Visit(concreteDef As ConcreteDefinition) As T
    Function Visit(continueStm As ContinueStatement) As T
    Function Visit(doLoopStm As DoLoopStatement) As T
    Function Visit(enumDef As EnumDefinition) As T
    Function Visit(exitStm As ExitStatement) As T
    Function Visit(expStm As ExpressionStatement) As T
    Function Visit(fieldDef As FieldDefinition) As T
    Function Visit(floatLiteral As FloatLiteralExpression) As T
    Function Visit(forEachStm As ForEachStatement) As T
    Function Visit(forStm As ForStatement) As T
    Function Visit(functionDef As FunctionDefinition) As T
    Function Visit(functionSignature As FunctionSignature) As T
    Function Visit(functionTypeName As FunctionTypeName) As T
    Function Visit(ifBlockStm As IfBlockStatement) As T
    Function Visit(ifThenStm As IfThenStatement) As T
    Function Visit(intLiteral As IntegerLiteralExpression) As T
    Function Visit(expLambdaBody As ExpressionLambdaBody) As T
    Function Visit(blockLambdaBody As BlockLambdaBody) As T
    Function Visit(lambdaExp As LambdaExpression) As T
    Function Visit(lambdaSignature As LambdaSignature) As T
    Function Visit(memberAccessExp As MemberAccessExpression) As T
    Function Visit(newArrayExp As NewArrayExpression) As T
    Function Visit(nothingExp As NothingExpression) As T
    Function Visit(operatorDef As OperatorDefinition) As T
    Function Visit(operatorSignature As OperatorSignature) As T
    Function Visit(paramDecl As ParameterDeclaration) As T
    Function Visit(primitiveTypeName As PrimitiveTypeName) As T
    Function Visit(procedureDecl As ProcedureDeclaration) As T
    Function Visit(qualifiedTypeName As QualifiedTypeName) As T
    Function Visit(refExp As ReferenceExpression) As T
    Function Visit(returnStm As ReturnStatement) As T
    Function Visit(selectCaseStm As SelectCaseStatement) As T
    Function Visit(strLiteral As StringLiteral) As T
    Function Visit(tryStm As TryStatement) As T
    Function Visit(typeConstraint As TypeConstraintClause) As T
    Function Visit(typeDef As TypeDefinition) As T
    Function Visit(unaryExp As UnaryExpression) As T
End Interface
